[package]
name = "binance"
version = "0.1.0"
authors = ["Arvid E. Picciani <aep@exys.org>"]

[dependencies]
websocket = "0.20.2"
futures = "0.1"
tokio-core = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
hyper = "0.11.7"
hyper-tls = "0.1.2"
